version: "3.8"
services:
  couchdb:
    image: couchdb:latest
    container_name: re-qoute-couch-db
    restart: always
    ports:
      - 2026:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ILoveKats123
    volumes:
      - couchdb_data:/opt/couchdb/data

  app:
    image: evilbyte/cdskill:latest
    container_name: cdskill
    restart: always
    ports:
      - 2025:2025
    depends_on:
      - couchdb
    environment:
      COUCHDB_URL: http://admin:ILoveKats123@couchdb:5984
      ENVIRONMENT: production

volumes:
  couchdb_data:
