name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t evilbyte/cdpipe:latest -f Dockerfile .

      - name: Push Docker Image
        run: docker push evilbyte/cdpipe:latest

      - name: Notify Discord on success
        if: ${{ success() }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ GitHub Actions succeeded on `${{ github.repository }}` for commit `${{ github.sha }}`"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on failure
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "❌ GitHub Actions failed on `${{ github.repository }}` for commit `${{ github.sha }}`"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}